version: "3.5"

services:
  postgres:
    container_name: postgres-test
    image: postgres:latest
    restart: always
    ports:
      - 5432:5432
    networks:
      - database
    volumes:
      - postgres-pd:/var/lib/postgresql/data
      - ./conf/postgres/create-user-and-db.sh:/docker-entrypoint-initdb.d/create-user-and-db.sh
    environment:
      POSTGRES_PASSWORD: postgres
      PGDATA: /var/lib/postgresql/data/pgdata
      TZ: "Europe/Rome"
      PGTZ: "Europe/Rome"

networks:
  database:
    name: database

volumes:
  postgres-pd:
    name: postgres-test
